import React from 'react';
import './home.css'

const Home = () => {
  return (
    <div className='home-container'>
      <h2>Bem-vindo ao Universo do Código e Inovação! 🚀</h2>
      <p>
        SEJA VOCÊ UM NOVATO CURIOSO OU UM MESTRE DO CÓDIGO, ESTOU EMPOLGADO EM COMPARTILHAR O MEU MUNDO DE DESENVOLVIMENTO E INOVAÇÃO CONTIGO. AQUI, NA JORNADA ATRAVÉS DOS BITS E BYTES, ENCONTRAREMOS NÃO APENAS LINHAS DE CÓDIGO, MAS TAMBÉM SOLUÇÕES CRIATIVAS, DESAFIOS INTRIGANTES E, É CLARO, UMA PITADA DE BOM HUMOR.
      </p>
      <p>
        DENTRO DESTE REINO DIGITAL, SOU O ARQUITETO DE LINHAS DE CÓDIGO QUE CONSTROEM PONTES ENTRE IDEIAS E REALIDADE. MINHA PAIXÃO PELO DESENVOLVIMENTO É MAIS DO QUE SIMPLESMENTE CRIAR; É SOBRE APRIMORAR EXPERIÊNCIAS, DESVENDAR POSSIBILIDADES E CONSTRUIR O FUTURO DIGITAL.
      </p>
      <p>
        DÊ UMA OLHADA AO REDOR, EXPLORE OS PROJETOS QUE GANHARAM VIDA COM DEDICAÇÃO E CRIATIVIDADE. ENCONTRE INSPIRAÇÃO NAS JORNADAS DE APRENDIZADO, NOS MOMENTOS DE RESOLUÇÃO DE PROBLEMAS E, CLARO, NOS PROJETOS QUE REFLETEM MEU COMPROMISSO COM A QUALIDADE E A INOVAÇÃO.
      </p>
      <p>
        ESTE É UM CONVITE PARA MERGULHAR NAS LINHAS DE CÓDIGO QUE CONTAM HISTÓRIAS, QUE DÃO VIDA A IDEIAS E TRANSFORMAM DESAFIOS EM OPORTUNIDADES. SEJA PARTE DESTA JORNADA, ONDE A MAGIA DA PROGRAMAÇÃO SE ENCONTRA COM A ARTE DA CRIAÇÃO. ESTOU ANSIOSO PARA COMPARTILHAR ESSA EXPERIÊNCIA FASCINANTE CONTIGO. 🌐💻✨
      </p>
      <p>VAMOS COMEÇAR ESSA INCRÍVEL JORNADA JUNTOS! 🚀🚀🚀</p>
</div>
  );
};

export default Home;
